name: arri_client
description: Client library for working with arri rpc server
version: "0.0.5"
repository: https://github.com/modiimedia/arri
environment:
    sdk: ">=3.0.0 <4.0.0"
dependencies:
    http: ">=0.13.0 <2.0.0"
dev_dependencies:
    lints: ^2.0.0
    test: ^1.21.0
