packages:
  - languages/**
  - playground/**
  - tooling/**
  - tests/**
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  nx: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - nx
  - typia
