// This file was autogenerated by @arrirpc/codegen-ts. Do not modify directly.
// For more information visit https://github.com/modiimedia/arri

/* eslint-disable */
// @ts-nocheck
import {
  ArriEnumValidator,
  ArriModelValidator,
  arriRequest,
  INT8_MAX,
  INT8_MIN,
  INT16_MAX,
  INT16_MIN,
  INT32_MAX,
  INT32_MIN,
  INT64_MAX,
  INT64_MIN,
  isObject,
  serializeString,
  UINT8_MAX,
  UINT16_MAX,
  UINT32_MAX,
  UINT64_MAX,
} from "@arrirpc/client";

type HeaderMap = Record<string, string | undefined>;
export class Client {
  private readonly _baseUrl: string;
  private readonly _headers: HeaderMap | (() => HeaderMap | Promise<HeaderMap>);

  constructor(
    options: {
      baseUrl?: string;
      headers?: HeaderMap | (() => HeaderMap | Promise<HeaderMap>);
    } = {},
  ) {
    this._baseUrl = options.baseUrl ?? "";
    this._headers = options.headers ?? {};
  }
  async SayHello(params: GreetingParams): Promise<GreetingResponse> {
    return arriRequest<GreetingResponse, GreetingParams>({
      url: `${this._baseUrl}/procedures/say-hello`,
      method: "get",
      headers: this._headers,
      params: params,
      responseFromJson: $$GreetingResponse.fromJson,
      responseFromString: $$GreetingResponse.fromJsonString,
      serializer: $$GreetingParams.toUrlQueryString,
      clientVersion: "",
    });
  }
  async SayGoodbye(params: GreetingParams): Promise<GreetingResponse> {
    return arriRequest<GreetingResponse, GreetingParams>({
      url: `${this._baseUrl}/procedures/say-goodbye`,
      method: "post",
      headers: this._headers,
      params: params,
      responseFromJson: $$GreetingResponse.fromJson,
      responseFromString: $$GreetingResponse.fromJsonString,
      serializer: $$GreetingParams.toJsonString,
      clientVersion: "",
    });
  }
}

export interface GreetingParams {
  name: string;
}
export const $$GreetingParams: ArriModelValidator<GreetingParams> = {
  new(): GreetingParams {
    return {
      name: "",
    };
  },
  validate(input): input is GreetingParams {
    return isObject(input) && typeof input.name === "string";
  },
  fromJson(input): GreetingParams {
    let _name: string;
    if (typeof input.name === "string") {
      _name = input.name;
    } else {
      _name = "";
    }
    return {
      name: _name,
    };
  },
  fromJsonString(input): GreetingParams {
    return $$GreetingParams.fromJson(JSON.parse(input));
  },
  toJsonString(input): string {
    let json = "{";
    json += '"name":';
    json += serializeString(input.name);
    json += "}";
    return json;
  },
  toUrlQueryString(input): string {
    const queryParts: string[] = [];
    queryParts.push(`name=${input.name}`);
    return queryParts.join("&");
  },
};

export interface GreetingResponse {
  message: string;
}
export const $$GreetingResponse: ArriModelValidator<GreetingResponse> = {
  new(): GreetingResponse {
    return {
      message: "",
    };
  },
  validate(input): input is GreetingResponse {
    return isObject(input) && typeof input.message === "string";
  },
  fromJson(input): GreetingResponse {
    let _message: string;
    if (typeof input.message === "string") {
      _message = input.message;
    } else {
      _message = "";
    }
    return {
      message: _message,
    };
  },
  fromJsonString(input): GreetingResponse {
    return $$GreetingResponse.fromJson(JSON.parse(input));
  },
  toJsonString(input): string {
    let json = "{";
    json += '"message":';
    json += serializeString(input.message);
    json += "}";
    return json;
  },
  toUrlQueryString(input): string {
    const queryParts: string[] = [];
    queryParts.push(`message=${input.message}`);
    return queryParts.join("&");
  },
};
