// this file was autogenerated by arri-codegen-ts
/* eslint-disable */
import { arriRequest } from "arri-client";

interface TestClientOptions {
  baseUrl?: string;
  headers?: Record<string, string>;
}

export class TestClient {
  private readonly baseUrl: string;
  private readonly headers: Record<string, string>;
  users: TestClientUsersService;
  posts: TestClientPostsService;

  constructor(options: TestClientOptions = {}) {
    this.baseUrl = options.baseUrl ?? "";
    this.headers = options.headers ?? {};
    this.users = new TestClientUsersService(options);
    this.posts = new TestClientPostsService(options);
  }
}

export class TestClientUsersService {
  private readonly baseUrl: string;
  private readonly headers: Record<string, string>;

  constructor(options: TestClientOptions = {}) {
    this.baseUrl = options.baseUrl ?? "";
    this.headers = options.headers ?? {};
  }
  SayHello() {
    return arriRequest<undefined, undefined>({
      url: `${this.baseUrl}/rpcs/users/say-hello`,
      method: "post",
      headers: this.headers,
      params: undefined,
      parser: (_) => {},
      serializer: (_) => {},
    });
  }
}

export class TestClientPostsService {
  private readonly baseUrl: string;
  private readonly headers: Record<string, string>;

  constructor(options: TestClientOptions = {}) {
    this.baseUrl = options.baseUrl ?? "";
    this.headers = options.headers ?? {};
  }
  getPost(params: PostsGetPostParams) {
    return arriRequest<Post, PostsGetPostParams>({
      url: `${this.baseUrl}/rpcs/posts/get-post`,
      method: "get",
      headers: this.headers,
      params,
      parser: (input) => $$Post.parse(JSON.parse(input)),
      serializer: $$PostsGetPostParams.serialize,
    });
  }
  getPosts(params: PostsGetPostsParams) {
    return arriRequest<PostsGetPostsResponse, PostsGetPostsParams>({
      url: `${this.baseUrl}/rpcs/posts/get-posts`,
      method: "get",
      headers: this.headers,
      params,
      parser: (input) => $$PostsGetPostsResponse.parse(JSON.parse(input)),
      serializer: $$PostsGetPostsParams.serialize,
    });
  }
  updatePost(params: PostsUpdatePostParams) {
    return arriRequest<Post, PostsUpdatePostParams>({
      url: `${this.baseUrl}/rpcs/posts/update-post`,
      method: "post",
      headers: this.headers,
      params,
      parser: (input) => $$Post.parse(JSON.parse(input)),
      serializer: $$PostsUpdatePostParams.serialize,
    });
  }
}

export interface PostsGetPostParams {
  postId: string;
}
export const $$PostsGetPostParams = {
  parse(input: Record<any, any>): PostsGetPostParams {
    return {
      postId: typeof input.postId === "string" ? input.postId : "",
    };
  },
  serialize(input: PostsGetPostParams): string {
    return JSON.stringify(input);
  },
};

export interface Post {
  id: string;
  title: string;
  type: PostType;
  description: string | null;
  content: string;
  tags: Array<string>;
  authorId: string;
  author: Author;
  createdAt: Date;
  updatedAt: Date;
}
export const $$Post = {
  parse(input: Record<any, any>): Post {
    return {
      id: typeof input.id === "string" ? input.id : "",
      title: typeof input.title === "string" ? input.title : "",
      type: $$PostType.parse(input.type),
      description:
        typeof input.description === "string" ? input.description : null,
      content: typeof input.content === "string" ? input.content : "",
      tags: Array.isArray(input.tags)
        ? input.tags.map((item) => (typeof item === "string" ? item : ""))
        : [],
      authorId: typeof input.authorId === "string" ? input.authorId : "",
      author: $$Author.parse(input.author),
      createdAt:
        typeof input.createdAt === "string"
          ? new Date(input.createdAt)
          : new Date(0),
      updatedAt:
        typeof input.updatedAt === "string"
          ? new Date(input.updatedAt)
          : new Date(0),
    };
  },
  serialize(input: Post): string {
    return JSON.stringify(input);
  },
};
export type PostType = "text" | "image" | "video";
export const $$PostType = {
  parse(input: any): PostType {
    const vals = ["text", "image", "video"];
    if (typeof input !== "string" || !vals.includes(input)) {
      throw new Error(
        `Invalid input for PostType. Expected one of the following [text, image, video]. Got ${input}.`,
      );
    }
    return input as PostType;
  },
  serialize(input: PostType): string {
    return input;
  },
};
export interface Author {
  id: string;
  name: string;
  bio: string | null;
  createdAt: Date;
  updatedAt: Date;
}
export const $$Author = {
  parse(input: Record<any, any>): Author {
    return {
      id: typeof input.id === "string" ? input.id : "",
      name: typeof input.name === "string" ? input.name : "",
      bio: typeof input.bio === "string" ? input.bio : null,
      createdAt:
        typeof input.createdAt === "string"
          ? new Date(input.createdAt)
          : new Date(0),
      updatedAt:
        typeof input.updatedAt === "string"
          ? new Date(input.updatedAt)
          : new Date(0),
    };
  },
  serialize(input: Author): string {
    return JSON.stringify(input);
  },
};

export interface PostsGetPostsParams {
  limit: number;
  type?: PostType;
}
export const $$PostsGetPostsParams = {
  parse(input: Record<any, any>): PostsGetPostsParams {
    return {
      limit: typeof input.limit === "number" ? input.limit : 0,
      type:
        typeof input.type === "string"
          ? $$PostType.parse(input.type)
          : undefined,
    };
  },
  serialize(input: PostsGetPostsParams): string {
    return JSON.stringify(input);
  },
};

export interface PostsGetPostsResponse {
  total: number;
  items: Array<Post>;
}
export const $$PostsGetPostsResponse = {
  parse(input: Record<any, any>): PostsGetPostsResponse {
    return {
      total: typeof input.total === "number" ? input.total : 0,
      items: Array.isArray(input.items)
        ? input.items.map((item) => $$Post.parse(item))
        : [],
    };
  },
  serialize(input: PostsGetPostsResponse): string {
    return JSON.stringify(input);
  },
};

export interface PostsUpdatePostParams {
  postId: string;
  data: PostsUpdatePostParamsData;
}
export const $$PostsUpdatePostParams = {
  parse(input: Record<any, any>): PostsUpdatePostParams {
    return {
      postId: typeof input.postId === "string" ? input.postId : "",
      data: $$PostsUpdatePostParamsData.parse(input.data),
    };
  },
  serialize(input: PostsUpdatePostParams): string {
    return JSON.stringify(input);
  },
};
export interface PostsUpdatePostParamsData {
  title: string;
  description: string | null;
  content: string;
  tags: Array<string>;
}
export const $$PostsUpdatePostParamsData = {
  parse(input: Record<any, any>): PostsUpdatePostParamsData {
    return {
      title: typeof input.title === "string" ? input.title : "",
      description:
        typeof input.description === "string" ? input.description : null,
      content: typeof input.content === "string" ? input.content : "",
      tags: Array.isArray(input.tags)
        ? input.tags.map((item) => (typeof item === "string" ? item : ""))
        : [],
    };
  },
  serialize(input: PostsUpdatePostParamsData): string {
    return JSON.stringify(input);
  },
};

export interface ErrorResponse {
  statusCode: number;
  statusMessage: string;
  stack: Array<any>;
  data?: any;
}
export const $$ErrorResponse = {
  parse(input: Record<any, any>): ErrorResponse {
    return {
      statusCode: typeof input.statusCode === "number" ? input.statusCode : 0,
      statusMessage:
        typeof input.statusMessage === "string" ? input.statusMessage : "",
      stack: Array.isArray(input.stack) ? input.stack.map((item) => item) : [],
      data: input.data,
    };
  },
  serialize(input: ErrorResponse): string {
    return JSON.stringify(input);
  },
};
