[package]
name = "arri-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.serde_json]
version = "1.0"

[dependencies.serde]
version = "1.0.196"
features = ["derive"]
