name: arri_codegen_dart_reference
description:
publish_to: none
repository: https://github.com/modiimedia/arri/tree/master/packages/arri-client-dart-reference
issue_tracker: https://github.com/modiimedia/arri/issues
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  arri_client:
    path: "../dart-client"
dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.12
