name: arri_codegen_dart_reference
description:
publish_to: none
repository: https://github.com/modiimedia/arri/tree/master/packages/arri-client-dart-reference
issue_tracker: https://github.com/modiimedia/arri/issues
environment:
  sdk: '>=3.7.0 <4.0.0'
dependencies:
  arri_client:
    path: '../dart-client'
dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
