name: arri
description:
version: "0.0.40"
publish_to: none
repository: https://github.com/modiimedia/arri/tree/master/packages/arri-client-dart
issue_tracker: https://github.com/modiimedia/arri/issues
environment:
    sdk: ">=3.0.0 <4.0.0"
dependencies:
    arri_client:
        path: "../arri-client-dart"
dev_dependencies:
    lints: ^2.0.0
    test: ^1.21.0
